// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviceB.proto

package service_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("serviceB.proto", fileDescriptor_4955967b6ceadeac) }

var fileDescriptor_4955967b6ceadeac = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x75, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x85, 0xf2, 0x21, 0x5c,
	0x29, 0x9e, 0xe4, 0xfc, 0xdc, 0xdc, 0xfc, 0x3c, 0x08, 0xcf, 0x28, 0x82, 0x8b, 0x23, 0x18, 0xaa,
	0x5c, 0xc8, 0x87, 0x8b, 0x25, 0x20, 0x33, 0x2f, 0x5d, 0x48, 0x51, 0x0f, 0xa6, 0x03, 0x59, 0xa9,
	0x9e, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x2a, 0x48, 0x89, 0x14, 0x01, 0x25, 0xf9, 0x79, 0xe9,
	0x4e, 0x82, 0x01, 0x8c, 0x51, 0xa8, 0x56, 0x27, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x72, 0xbc, 0x3f, 0xff, 0xa2, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceBClient is the client API for ServiceB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceBClient interface {
	Ping(ctx context.Context, in *MessagePing, opts ...grpc.CallOption) (*MessagePong, error)
}

type serviceBClient struct {
	cc *grpc.ClientConn
}

func NewServiceBClient(cc *grpc.ClientConn) ServiceBClient {
	return &serviceBClient{cc}
}

func (c *serviceBClient) Ping(ctx context.Context, in *MessagePing, opts ...grpc.CallOption) (*MessagePong, error) {
	out := new(MessagePong)
	err := c.cc.Invoke(ctx, "/service.proto.ServiceB/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceBServer is the server API for ServiceB service.
type ServiceBServer interface {
	Ping(context.Context, *MessagePing) (*MessagePong, error)
}

// UnimplementedServiceBServer can be embedded to have forward compatible implementations.
type UnimplementedServiceBServer struct {
}

func (*UnimplementedServiceBServer) Ping(ctx context.Context, req *MessagePing) (*MessagePong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterServiceBServer(s *grpc.Server, srv ServiceBServer) {
	s.RegisterService(&_ServiceB_serviceDesc, srv)
}

func _ServiceB_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceBServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.proto.ServiceB/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceBServer).Ping(ctx, req.(*MessagePing))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.proto.ServiceB",
	HandlerType: (*ServiceBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ServiceB_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceB.proto",
}
